name: Build ZuluControl-firmware

on:
  push:
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      
      - name: Checkout pico-sdk
        uses: actions/checkout@v7
        with:
          repository: raspberrypi/pico-sdk
          path: pico-sdk
          
      - name: Checkout pico-sdk submodules
        working-directory: pico-sdk
        run: git submodule update --init

      - name: Setup Tools
        run: |
           sudo apt update
           sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential
           
      - name: Build
        env:
          PICO_SDK_PATH: ${{github.workspace}}/pico-sdk
        run: |
          cd universal_binary
          cmake -B build
          cmake --build build

      - name: Upload UF2 into build artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ${{github.workspace}}/universal_binary/build/zulucontrol.uf2
          name: ZuluControl-firmware universal binary

      - name: Upload ELFs into build artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ${{github.workspace}}/universal_binary/build/platform_*/*.elf
          name: Debugging symbols

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Upload to latest release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref == 'refs/heads/main'
        run: |
          cd universal_binary/build
          gh release create  --latest --repo ${GITHUB_REPOSITORY} release-${{steps.date.outputs.date}}-${{github.run_id}} zulucontrol.uf2

      - name: Upload to newly created release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          RELEASE=$(basename ${{github.ref}})
          cd universal_binary/build
          gh release upload --repo ${GITHUB_REPOSITORY} $RELEASE * zulucontrol.uf2
